### ISSUE TITLE
Disabling and reenabling camera fails.

### ISSUE THREAD

**Issue by davidliu** [livekit/client-sdk-react-native#10]
Results in:

```
Error: unable to restart an unpublished track.
```

**Comment by aimin-git** [comment]
@davidliu any plan in fixing this issue soon? Thanks.

**Comment by davidliu** [comment]
Yeah, I'll be taking a look at this next.

**Comment by aimin-git** [comment]
Thanks. Curious to me that the latest tag in github is v1.0.0, where can I get the code for 1.1.9?
