### ISSUE TITLE
Capture image from local camera

### ISSUE THREAD

**Issue by ciaoamigoschat** [livekit/client-sdk-react-native#100]
How to capture an image from the local camera while streaming.

**Comment by b0iq** [comment]
Try this one https://github.com/gre/react-native-view-shot.
I'm using it to make image from Views and it works perfectly

**Comment by ciaoamigoschat** [comment]
The component https://github.com/gre/react-native-view-shot. captures the image of the view, therefore using the current dimensions of the view. I need to capture the image of the local camera, with the dimensions I am transmitting

**Comment by davidliu** [comment]
This isn't possible, due to the limitations with the react-native-webrtc library. You might want to file an issue there.
