### ISSUE TITLE
Exporting local "AudioConfiguration", which is not declared.

### ISSUE THREAD

**Issue by sarmatkasaev** [livekit/client-sdk-react-native#102]
when I try to run the project, I get an error

error: node_modules/@livekit/react-native/src/index.tsx: /Users/user/Documents/Projects/unic.chat.mobile/node_modules/@livekit/react-native/src/index.tsx: Exporting local "AudioConfiguration", which is not declared.
  74 | export {
  75 |   AudioSession,
      76 |   AudioConfiguration,
     |   ^^^^^^^^^^^^^^^^^^
  77 |   AndroidAudioTypeOptions,
  78 |   AndroidAudioTypePresets,
  79 | };
info Reloading app...
 BUNDLE  ./index.js

**Comment by sarmatkasaev** [comment]
error changed to [Cannot read properties of undefined (reading 'split')](https://github.com/livekit/client-sdk-react-native#cannot-read-properties-of-undefined-reading-split)

**Comment by FarmersReact** [comment]
> error changed to [Cannot read properties of undefined (reading 'split')](https://github.com/livekit/client-sdk-react-native#cannot-read-properties-of-undefined-reading-split)

me too
