### ISSUE TITLE
App crashes during codepush update in android

### ISSUE THREAD

**Issue by wjaykim** [livekit/client-sdk-react-native#105]
**Describe the bug**

App crashes while applying codepush update in android. More specifically, after codepush finishes downloading new js bundle, app crashes while restarting to apply new js bundle.

It occured after https://github.com/livekit/client-sdk-react-native/commit/32cf80bad57c60eeabb257744945fb5dee18e715 commit;
When I delete [these lines](https://github.com/livekit/client-sdk-react-native/commit/32cf80bad57c60eeabb257744945fb5dee18e715#diff-fb5b32ac2dd8f56e0285809670b01c5442dd174bf67aa6817116ea091040476fR29-R33), codepush works without crash.

**To Reproduce**

1. Apply codepush update(`InstallMode.IMMEDIATE`)

**Expected behavior**

App should not crash

**Screenshots**

**Device Info:**

 - Device: All android devices
 - OS: Android

**Dependencies Info (please reference your package-lock.json or yarn.lock file):**

 - @livekit/react-native: 1.3.0
 - livekit-client: 1.13.2
 - react-native-webrtc: 104.0.1

**Additional context**

**Comment by wjaykim** [comment]
https://github.com/react-native-webrtc/react-native-webrtc/pull/1456

This issue can be fixed by above PR.

**Comment by davidliu** [comment]
The plan is to periodically sync with the origin repo. I'll sync after the next release.

**Comment by davidliu** [comment]
livekit/react-native-webrtc is now synced to the 111.0.6 release.
