### ISSUE TITLE
Reduce the client sdk size by providing different component as installable plugins

### ISSUE THREAD

**Issue by nateshmbhat** [livekit/client-sdk-react-native#106]
Right now, this sdk is increasing our app size by around 35 MBs but we are only using this to send just camera feed without any audio or screen sharing or other features. 

so it would be great if you can provide a way to install individual components for different use cases and needs since this is a big sdk

**Comment by davidliu** [comment]
We won't be able to provide this since it's a pretty big piece of maintenance work to provide multiple versions of WebRTC. However, 35MB app size increase is a lot bigger than what we see on our end. Which platform are you seeing the app size increase on?

**Comment by nateshmbhat** [comment]
Android apk

**Comment by davidliu** [comment]
AAB files aren't representative of the final APK size. In particular, the AAB will have the native webrtc libraries for various architectures (i.e. ARMv7, ARM64, x86 etc), but the final APK will only contain the library for the device it's downloaded to (assuming you're going through the play store or another app store that's compatible with app bundles).

See [Bundletool](https://developer.android.com/tools/bundletool#measure_size) for properly testing the size of your final app size. We see around 4-5MB size increase when tested in this manner.
