### ISSUE TITLE
Cannot build ios app

### ISSUE THREAD

**Issue by wjaykim** [livekit/client-sdk-react-native#115]
**Describe the bug**

Some APIs available from WebRTC M111 release such as `RTCAudioDevice` is referenced in react-native-webrtc, but it seems livekit's react-native-webrtc is using M104 release(https://github.com/livekit/react-native-webrtc/commit/31a19e2944b780b6388463b2ad24f16b0097df08), thus causing build failing.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Device Info:**

**Dependencies Info (please reference your package-lock.json or yarn.lock file):**

 - @livekit/react-native: 1.4.0
 - livekit-client:
 - react-native-webrtc: 114.0.0

**Additional context**

**Comment by wjaykim** [comment]
It's still failing. It seem's it's still installing M104 because of this line:
https://github.com/livekit/react-native-webrtc/blob/31a19e2944b780b6388463b2ad24f16b0097df08/livekit-react-native-webrtc.podspec#L22

**Comment by wjaykim** [comment]
FYI: If i change the version in podspec, build successes, but camera stream is always in landscape mode, not respecting orientation of device. (only in ios)

**Comment by davidliu** [comment]
Hmm, is `@livekit/react-native-webrtc` properly 114.0.0? That file should look like this:

https://github.com/livekit/react-native-webrtc/blob/89d8704627d9e352f89150d93453274651001728/livekit-react-native-webrtc.podspec

The 114 releases go off the `v114` branch at the moment, haven't synced with master yet, but you can see the state of the code from the [tags](https://github.com/livekit/react-native-webrtc/tags) page. If it's still referring to 104, that'd be really weird. Are you by any chance grabbing `react-native-webrtc` by git url?
