### ISSUE TITLE
Sound can't go to 0 (muted) on iOS and Android

### ISSUE THREAD

**Issue by Spharian** [livekit/client-sdk-react-native#137]
**Describe the bug**

When changing volume on a device, the volume can't go to 0 (tested on iOS and Android). It feels like a "minimum volume" is set somewhere.

**To Reproduce**

1. Use the `VideoView` component:
```
<VideoView
  style={{
    flex: 1,
    backgroundColor: Colors.black,
  }}
  objectFit="cover"
  videoTrack={streamerParticipant.getTrackPublication(Track.Source.Camera)?.videoTrack}
/>
```
2. Try to reduce the volume to the minimum on iOS or Android, the sound is never muted (volume to 0) as it should be. 

**Expected behavior**

The volume should go to 0 and we shouldn't hear the remote participant.

**Device Info:**

 - Device: iPhone 15 Pro (but other iPhones too) 
 - OS: ios 17.4.1

**Dependencies Info (please reference your package-lock.json or yarn.lock file):**

 - @livekit/react-native: 2.0.1
 - livekit-client: 2.0.5
- @livekit/react-native-webrtc: 114.0.0

**Comment by Spharian** [comment]
Solved by configuring: https://github.com/livekit/client-sdk-react-native?tab=readme-ov-file#kotlin
Using Expo, this is forcing me to keep an android folder and not having it in the .gitignore then Expo take in into account for builds.

**Comment by davidzhao** [comment]
Thanks for the update @Spharian, it's on our roadmap to make Expo integration a lot easier! @davidliu

**Comment by stephendhughes** [comment]
Hello!

I'm also seeing this issue with the expo integration - is there a way to do this using expo?
