### ISSUE TITLE
Expo 50 compatibilty.

### ISSUE THREAD

**Issue by geoffcfchen** [livekit/client-sdk-react-native#145]
Are there any updates about expo 50 compatibility? I know that we can only use it for expo 50 according to Wiki, but Apple require everyone upgrade to expo 50 for new SDK. It would be great if we can use LiveKit in expo 50 environment. Thanks.

**Comment by davidliu** [comment]
Hey, sorry, that wiki page is out of date. I'll update it when I'm back in the office, but expo 50 should be supported with the latest version.
