### ISSUE TITLE
Unable to put in earpiece mode from speaker in IOS

### ISSUE THREAD

**Issue by kmamtora** [livekit/client-sdk-react-native#149]
`await AudioSession.selectAudioOutput(isSpeaker === "speaker" ? "earpiece" : "speaker");`

from loudspeaker to phone I am unable to change it in IOS in android this code works fine .

**Comment by davidliu** [comment]
ios does not share the same audio device ids as android.

See [AudioSession.getAudioOutputs()](https://htmlpreview.github.io/?https://raw.githubusercontent.com/livekit/client-sdk-react-native/main/docs/classes/AudioSession.html#getAudioOutputs).
