### ISSUE TITLE
Audio output selection

### ISSUE THREAD

**Issue by davidliu** [livekit/client-sdk-react-native#15]

**Comment by petyots** [comment]
Any progress on that? Thanks for the lib btw

**Comment by vithubati** [comment]
Thanks you for the library. its such an amazing work you guys are doing. I am also looking for the same feature support. I was hoping if you guys could give us any timeline for this feature if possible. 
Thanks you

**Comment by davidliu** [comment]
Starting work on this now. iOS is a little hairy since audio output selection is a bit limited there.

**Comment by davidliu** [comment]
Addressed in #18.

**Comment by vithubati** [comment]
Thank you for the prompt action. You are amazing!

**Comment by Mihai-github** [comment]
@davidliu Is there a way for us to detect the currently active audio output?
A client asked if it’s possible to display which output is currently in use when presenting the list of available audio output options.
