### ISSUE TITLE
[Feature Request] Does LiveKit support closed captions?

### ISSUE THREAD

**Issue by goatandsheep** [livekit/client-sdk-react-native#161]
**Is your feature request related to a problem? Please describe.**
I'm building an application that demonstrates a new feature of closed captions.

**Describe the solution you'd like**
A way to listen for closed captions / subtitle hide / show / change events

**Describe alternatives you've considered**
None yet

**Additional context**
I am new to this and I'm procuring solutions.

**Comment by davidliu** [comment]
Are you asking for live transcriptions from AI agents? We offer that here: https://docs.livekit.io/agents/overview/

We don't have any UI components for showing transcriptions at the moment if that's what you're asking, but it's on the roadmap. That said, it shouldn't be too hard to show the latest transcription received in a Text component.

**Comment by goatandsheep** [comment]
Hi no it was not for AI but from the stream. I will be streaming multiple captions tracks in the HLS stream. I was wondering if the component already supports captions but I see it does not
