### ISSUE TITLE
FOREGROUND_SERVICE_MEDIA_PROJECTION being added to the app

### ISSUE THREAD

**Issue by radko93** [livekit/client-sdk-react-native#171]
**Describe the bug**

With 2.4.0 `FOREGROUND_SERVICE_MEDIA_PROJECTION` permission is being added even if the app does not implement it. This is problematic because Google requires all use of Foreground service to only be declared when actually in use. This has to be proven with a video. 

It's possible to workaround this by adding this line to AndroidManifest of the app but it's not ideal:
`<uses-permission android:name="android.permission.FOREGROUND_SERVICE_MEDIA_PROJECTION" tools:node="remove" />`

Google Play Console screenshot:
![image](https://github.com/user-attachments/assets/d128066d-fe48-40fc-bc14-e25ad9c3107b)

**Comment by davidliu** [comment]
Agh, didn't realize it'd be an issue on the Google Play side, I'll remove.

**Comment by davidliu** [comment]
2.4.1 is released with this fix.
