### ISSUE TITLE
Black screen issue on ios 

### ISSUE THREAD

**Issue by ngdlmk** [livekit/client-sdk-react-native#176]
**Describe the bug**
IOS only
Camera view becomes black on ios but it is working fine on android. Only local camera view is black if I connect to room from android or web it shows remote camera on ios but local is not working looks lite it is related with RTCView I have tested with it also it is black.  
also getting this error 

could not determine track dimensions, using defaults {"dims": {"height": 720, "width": 1280}, "enabled": true, "kind": "video", "muted": false, "pID": "PA_5CWK268jThim", "participant": "pirate", "room": "okinawa", "roomID": "", "source": "camera", "streamID": "4254EEB0-5758-42D3-969C-0BFBEBAD41E6", "streamTrackID": "4254EEB0-5758-42D3-969C-0BFBEBAD41E6", "trackID": undefined}

**Expected behavior**
When I run the app it should show camera view on the screen but it becomes black. 

**Screenshots**
![Simulator Screenshot - iPhone 15 Pro Max - 2024-10-01 at 01 21 56](https://github.com/user-attachments/assets/a9f5f79d-be6c-43ef-916e-6d189000ca72)

**Device Info:**

 - Device: [e.g. iPhone Pro Max 12]
 - OS: [e.g. iOS17.6.1]

**Dependencies Info (please reference your package-lock.json or yarn.lock file):**

    "@livekit/react-native": "^2.4.2",
    "@livekit/react-native-webrtc": "^125.0.4",
    "livekit-client": "^2.5.5",
    "react": "18.2.0",
    "react-native": "0.74.2"

**Comment by arekkubaczkowski** [comment]
I was investigating this issue and found out that it is related to the latest release of: https://github.com/webrtc-sdk/Specs/releases/tag/125.6422.05

My temporary solution is to patch the dependency to force the previous version:
```
diff --git a/node_modules/@livekit/react-native-webrtc/livekit-react-native-webrtc.podspec b/node_modules/@livekit/react-native-webrtc/livekit-react-native-webrtc.podspec
index 775d869..a53423d 100644
--- a/node_modules/@livekit/react-native-webrtc/livekit-react-native-webrtc.podspec
+++ b/node_modules/@livekit/react-native-webrtc/livekit-react-native-webrtc.podspec
@@ -19,5 +19,5 @@ Pod::Spec.new do |s|
   s.libraries           = 'c', 'sqlite3', 'stdc++'
   s.framework           = 'AudioToolbox','AVFoundation', 'CoreAudio', 'CoreGraphics', 'CoreVideo', 'GLKit', 'VideoToolbox'
   s.dependency          'React-Core'
-  s.dependency          'WebRTC-SDK', '~>125.6422.02'
+  s.dependency          'WebRTC-SDK', '125.6422.04'
 end
```

However I am still experiencing some issues with back camera which freezes (front camera works fine)

**Comment by arekkubaczkowski** [comment]
for camera switching issue: I have not idea why it worked but I needed to clone the original VideoTrack component (without any changes) and import it instead of the original one and magically it started working again... 
I would be grateful for any ideas... The only thing that comes to my mind is that local file might be compiled differently than files from node_modules, however I have not clue why...

**Comment by ngdlmk** [comment]
I haven’t tested camera switching but solution is working fine for me too thanks @arekkubaczkowski

**Comment by davidliu** [comment]
@arekkubaczkowski thanks for investigating, will have time to look at this tomorrow.

**Comment by davidliu** [comment]
Hmm, I'm not able to repro this with WebRTC-SDK 125.6422.05.

Would it be possible for one of you to supply a repro project? Also, can you check against the example project in this repo?

**Comment by mosamlife** [comment]
I am experiencing the same issue! will provide more info after trying the above patch

**Comment by davidliu** [comment]
@mosamlife it would be **really** helpful if you could provide an repro project. I won't be able to help here until a repro project is given.

**Comment by Spharian** [comment]
Temporary fix: build the project first through Xcode and don't set the `ios` folder in `.gitignore` to make sure expo uses it during eas build.

**Comment by namnm** [comment]
> Hmm, I'm not able to repro this with WebRTC-SDK 125.6422.05.
> 
> Would it be possible for one of you to supply a repro project? Also, can you check against the example project in this repo?

We confirm to have this bug with ios 18

**Comment by namnm** [comment]
@davidliu repository to reproduce:
https://github.com/namnm/livekit-bug/blob/main/App.tsx

- ios 18 iphone 16 pro max simulator
- xcode 16A242d
- macos 15.0.1 24A348

**Comment by mosamlife** [comment]
@namnm  Thanks for providing the repo from your side. 

@davidliu  the issue with ios 18. on ios 17 works fine

**Comment by davidliu** [comment]
Should note that the camera does not work with the simulator.

**Comment by davidliu** [comment]
>@davidliu repository to reproduce:
https://github.com/namnm/livekit-bug/blob/main/App.tsx

@namnm Hmm, I'm unable to reproduce this on my device. 

Can you grab the logs from XCode when you run the app and get a repro? (The logs specifically must be from XCode, and not from the react native JS logs.)

Additionally, it would be helpful to turn on debug logs:

In your `index.js` file, add the following:

```
import { LogLevel, setLogLevel } from 'livekit-client';

setLogLevel(LogLevel.debug);
```

In your AppDelegate.m file:

```
#import "WebRTCModule.h"
#import "WebRTCModuleOptions.h"

@implementation AppDelegate

- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
  // Add the following to turn on logging
  WebRTCModuleOptions *options = [WebRTCModuleOptions sharedInstance];
  options.loggingSeverity = RTCLoggingSeverityInfo;
  ...
}
```

**Comment by davidliu** [comment]
K, finally got a repro. Looks like the issue was caused by not supporting multi-cam phones correctly (I only had a single camera device which is why it wasn't reproing). Will push out a fix soon.

**Comment by Spharian** [comment]
> K, finally got a repro. Looks like the issue was caused by not supporting multi-cam phones correctly (I only had a single camera device which is why it wasn't reproing). Will push out a fix soon.

Congrats 👏
