### ISSUE TITLE
Android app couldn't open in build version

### ISSUE THREAD

**Issue by Parathantl** [livekit/client-sdk-react-native#19]
As described in the README file, I have build the app and able test the app in development mode. Video & Audio everything was fine. But when I build the app and installed the APK and triend to open the app. But the app is not open it just closes the app from opening

**To Reproduce**
1. Build the app with **./gradlew assembleRelease** inside android directory in the app
2. Open the app : The app doesn't open up

**Expected behavior**
The app should open up

**Device Info (please complete the following information):**
 - Device: Samsung Galaxy M13
 - OS: Android 12
 
Dependencies used in the **package.json** are
 - "livekit-react-native": "^0.8.0",
 - "livekit-react-native": "github:livekit/client-sdk-react-native"
When I removed these dependencies and rebuild and tried, the app opens.

    "react": "17.0.1",
    "react-native": "0.64.2",
These are the versions I used in package.json

**I am using NPM as package manager. In documentation it uses yarn to do package managing**

**Comment by Parathantl** [comment]
It seems working now after configuring react-native-web-rtc library's requirement:
https://github.com/react-native-webrtc/react-native-webrtc/blob/master/Documentation/AndroidInstallation.md

I am closing this issue.

**Comment by Parathantl** [comment]
It would be helpful for people using this developers to mention to follow & configure react-native-webrtc configuration in build mode to work without any issue
 https://github.com/react-native-webrtc/react-native-webrtc/blob/master/Documentation

**Comment by davidzhao** [comment]
@Parathantl thanks for the heads up, we'll update our docs to reflect this

**Comment by davidliu** [comment]
Reopening so this doesn't get lost.
