### ISSUE TITLE
iOS: Dev works errors happens when archived

### ISSUE THREAD

**Issue by Parathantl** [livekit/client-sdk-react-native#21]
**Describe the bug**
The development is working good as expected but when we tried to archive the iOS version following error occurs.

![image](https://user-images.githubusercontent.com/5859130/188811609-53a592da-3e7d-40e0-b690-07de702b6e6e.png)

**To Reproduce**
Build the iOS app and archive it

**Expected behavior**
The app should be able to archive successfully

No any issues with mobile devices. The archive couldn't build to publish in the Testflight

**Additional context**
We are using https://github.com/livekit/react-native-webrtc#dl/wip-transceiver as react-native-webrtc.

https://github.com/react-native-webrtc/react-native-webrtc/issues/910: The issue we found in the react-native-webrtc GitHub page.
We tried remove Pod File and reinstalled the Pod

The coco-pod version is 1.11 (Latest stable version)

**Comment by davidliu** [comment]
Hmm, I'm not able to reproduce this on a fresh react-native project. Could you try reproducing this on a fresh react-native project and uploading it to github?

My cocoapod version is 1.11.3.

**Comment by Parathantl** [comment]
Closing this issue, since its from my end with using different modules
