### ISSUE TITLE
When AudioSession.startAudioSession() called the app crashes without errors

### ISSUE THREAD

**Issue by Parathantl** [livekit/client-sdk-react-native#22]
**Describe the bug**
When the AudioSession.startAudioSession() is called the app crashes and closes without any error in the  development.

**To Reproduce**

Following code I added to make output to default to speaker

`const room = await new Room({ publishDefaults: { simulcast: false }, adaptiveStream: true })`
`AudioSession.startAudioSession();`
`await AudioSession.selectAudioOutput("speaker");`
`room.connect(......) // connecting to a room `

When I tried to console the AudioOutput by
`        console.log('Available Outputs: ', await AudioSession.getAudioOutputs());
`

**It returns empty array**
That means no speaker or earpiece available?

Eventhough, by default both Android & iOS Audio Output set to speaker the doesn't works still the default is by earpiece

Any perquisite configurations needs to be done in android folder?

**Device Info (please complete the following information):**
 - Device: Samsung Galaxy M13
 -  OS: Android 12
 
- React Version: 17.0.1
-  "react-native": "0.64.2"

**Comment by Parathantl** [comment]
I tried putting `await` in-front of `AudioSession.startAudioSession()`
Not working.
Still the app crashes. When I removes  `AudioSession.startAudioSession()` the app works fine.
The output of audio is still earpiece.

**Any configurations needs to be done in the android folder?**

**Comment by Parathantl** [comment]
I have changed the example code. I am using JS instead of TypeScript in my project. Therefore, I changed the example code to JS.

[](https://github.com/Parathantl/livekit_demo)

I couldn't able to get the Audio Output to speaker. If I put `AudioSession` the app crashes.

**Comment by davidliu** [comment]
Is there no errors logged in logcat? There's generally always an exception emitted in the crash logs.

**Comment by davidliu** [comment]
I ran your demo, and it works fine on my device, defaulting to speaker as well as being able to change the audio output. I'll need some logs to see what the issue is.

**Comment by Parathantl** [comment]
I attached 2 images of

1. Connected Log from the Log cat in the command line:
![Connected Log](https://user-images.githubusercontent.com/5859130/189549027-52709d3b-97d9-4e24-8830-87f6fc5c5110.png)

2. Crashing popup from mobile view:
![Crash in mobile](https://user-images.githubusercontent.com/5859130/189549029-b6fd0697-a55a-43f6-a004-471c70225403.jpg)

Tested mobile is:
Samsung Galaxy M13

**Comment by davidliu** [comment]
This is missing the actual crash exception. Please copy and paste the unfiltered logs start to finish. 

* If you're using `npx react-native log-android`, please switch to directly using `adb logcat` to get the unfiltered logs.

**Comment by Parathantl** [comment]
Please find the below log file:
[logcat-for-debugging.txt](https://github.com/livekit/client-sdk-react-native/files/9544653/logcat-for-debugging.txt)

**Comment by Parathantl** [comment]
**I tested on Samsung Galaxy A70 and it works as expected. default to speaker as well as connects to the room too**
But in Samsung Galaxy M13 the app crashes.

**Comment by davidliu** [comment]
Can you check your app's permission page in the settings app to see if your Bluetooth/Nearby Devices permissions disabled?

**Comment by Parathantl** [comment]
Permissions are fine looks same in both mobiles.

Same build works in A70 and in M13 crashes but it get connects to the room

**Comment by davidliu** [comment]
Can you manually add the following lines to your `android/src/main/AndroidManifest.xml` file:

````
    <uses-permission android:name="android.permission.BLUETOOTH" android:maxSdkVersion="30" />
    <uses-permission android:name="android.permission.BLUETOOTH_ADMIN" android:maxSdkVersion="30" />
    <uses-permission android:name="android.permission.BLUETOOTH_CONNECT" />
````

**Comment by Parathantl** [comment]
I tested with this change now. Still crash occurs

**Comment by davidliu** [comment]
Can you try it without the maxSdkVersion attributes like so?

````
    <uses-permission android:name="android.permission.BLUETOOTH" />
    <uses-permission android:name="android.permission.BLUETOOTH_ADMIN" />
    <uses-permission android:name="android.permission.BLUETOOTH_CONNECT" />
````

**Comment by Parathantl** [comment]
This one also didn't solved the issue.
I build the app and tested the APK. That works without any crash. 

It is something related to development issue.

**Comment by davidliu** [comment]
Uninstall and reinstall your dev app. I think you've somehow disabled the bluetooth perms for the app. 

If that still doesn't work, then this is likely an issue with the phone itself, since the bluetooth permission should be granted by default for target api 29.
