### ISSUE TITLE
FATAL EXCEPTION: EglRenderer

### ISSUE THREAD

**Issue by marcosdourado** [livekit/client-sdk-react-native#23]
**Describe the bug**
My application is one-to-one, but different from the traditional one, the users' video alternates, that is, the first user speaks for 30 seconds and only his video and audio is displayed, then the second user speaks for 30 seconds and only its audio and video is displayed.

The approach I took was to not display the VideoView, I also tried to set the width and height to 0, it works once, but then it has some errors and then it crashes.

One message that appears is visibility resize observer not triggered. Am I using the proper approach? Or should I remove the track from the user and then subscribe to it again?

**To Reproduce**
Try switching between videos, not playing them and then playing them normally. 
Remembering that the video is 100% width and height.

**Expected behavior**
The videos should alternate smoothly considering what is said in the documentation, that when the video does not appear it is "paused".

**Screenshots**
FATAL EXCEPTION: EglRenderer

android.opengl.GLException: Failed to create window surface: 0x3000

FATAL EXCEPTION: EglRenderer
Process: br.com.simplevideo, PID: 32500
android.opengl.GLException: Failed to create window surface: 0x3000
	at org.webrtc.EglBase14Impl.createSurfaceInternal(EglBase14Impl.java:107)
	at org.webrtc.EglBase14Impl.createSurface(EglBase14Impl.java:85)
	at org.webrtc.EglRenderer$EglSurfaceCreation.run(EglRenderer.java:76)
	at android.os.Handler.handleCallback(Handler.java:790)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at org.webrtc.EglRenderer$HandlerWithExceptionCallback.dispatchMessage(EglRenderer.java:103)
	at android.os.Looper.loop(Looper.java:164)
	at android.os.HandlerThread.run(HandlerThread.java:65)

**Device Info (please complete the following information):**
 - Device: Android Emulator
 - OS: Android 8.1.0
-  livekit-client: 1.4.1
 - livekit-react-native: https://github.com/livekit/client-sdk-react-native

**Comment by marcosdourado** [comment]
Using RTCView directly, this problem does not occur, so I believe that the problem is associated with the visibility detection that occurs in VideoView.

**Comment by davidliu** [comment]
Sorry, could you provide a code snippet of the situation that errors? Seems like you mentioned a couple different attempts.

----

Does just having one VideoView and changing the track that's played through work?

**Comment by davidliu** [comment]
Closing as stale.
