### ISSUE TITLE
Cannot read property 'connectionQuality` of undefined

### ISSUE THREAD

**Issue by marcosdourado** [livekit/client-sdk-react-native#24]
**Describe the bug**
Algumas vezes em que estava executando o projeto, recebi o seguinte erro Cannot read property 'connectionQuality` of undefined.

**To Reproduce**
I was unable to repeat the steps to repeat the error.

**Expected behavior**
It is expected that this error will not occur, even if for some reason the participant is undefined. This occurred during the call.
I believe that such an error is possible to be corrected by checking if participant inside usePartipant is valid, perhaps with the optional-chaining operator? PRs welcome?

**Screenshots**
![Screenshot_1665152741](https://user-images.githubusercontent.com/4989884/194578832-336ecff8-2a60-4810-b23c-deb5c4315d8a.png)

**Device Info (please complete the following information):**
 - Device: Android Emulator
 - OS: Android 8.1.0
-  livekit-client: 1.4.1
 - livekit-react-native: https://github.com/livekit/client-sdk-react-native

**Comment by davidliu** [comment]
I don't think this will make much sense to do; the state itself becomes meaningless if an undefined participant is passed in.
