### ISSUE TITLE
Issue with track subscription on iOS

### ISSUE THREAD

**Issue by gladbhex** [livekit/client-sdk-react-native#30]
Hi

The following error is logged while joining

_unable to subscribe because MediaStreamTrack is ended. Do not call MediaStreamTrack.stop()_

The video view is black but can hear audio from the remote track.

client-sdk-react-native -> latest
react-native-webrtc -> 106.0.0-beta.5
iOS -> 16.1
react-native -> 0.69.5

rolling back to react-native-webrtc to https://github.com/livekit/react-native-webrtc.git#dl/wip-transceiver worked, no longer gave any errors, and was able to subscribe to tracks. 
Tried using a couple of other beta versions of react-native-webrtc, the error did not appear but the issue persists.

Thank you for the great work.

**Comment by davidzhao** [comment]
@gladbhex in your app, do you call MediaStreamTrack.stop() at any point?

**Comment by gladbhex** [comment]
No, not calling this anywhere.

**Comment by davidzhao** [comment]
Thanks, we'll investigate.

**Comment by davidzhao** [comment]
@davidliu the issue is [here](https://github.com/react-native-webrtc/react-native-webrtc/blob/master/ios/RCTWebRTC/SerializeUtils.m#L163), where it's returning `Live` when it's checking for lowercase `live` [here](https://github.com/react-native-webrtc/react-native-webrtc/blob/master/src/MediaStreamTrack.ts#L41)

**Comment by davidliu** [comment]
@davidzhao The line before that, they turn it to lowercase, so I don't think that's the cause.

**Comment by davidliu** [comment]
Related: https://github.com/react-native-webrtc/react-native-webrtc/issues/1219

**Comment by davidliu** [comment]
Fixed as of react-native-webrtc 106.0.0-beta-6
