### ISSUE TITLE
could not get audio sender stats

### ISSUE THREAD

**Issue by surya-sanity** [livekit/client-sdk-react-native#34]
On unmuting either audio or video throws error, functionalities works but throwing error. 
{"error": [TypeError: this.sender.getStats is not a function. (In 'this.sender.getStats()', 'this.sender.getStats' is undefined)]}

**To Reproduce**
1. Click on toggleVideo or toggleAudio
2. See error

**Expected behavior**
On unmuting should not throw the {"error": [TypeError: this.sender.getStats is not a function. (In 'this.sender.getStats()', 'this.sender.getStats' is undefined)]} error.

**Screenshots**
![](https://user-images.githubusercontent.com/73512695/201713121-35b79fdf-8599-410a-9f37-88e558cb6b85.png)

**Device Info**
- Development System - mac mini m1
 - Device: Poco F1 (Android)
 - OS: [Android 12]
 - LiveKit Version [1.5.0]

**Comment by davidliu** [comment]
This should be fixed as of the latest react-native-webrtc release.
