### ISSUE TITLE
Audio on android forced to system speaker

### ISSUE THREAD

**Issue by donaldkwong** [livekit/client-sdk-react-native#38]
**Describe the bug**

When connected to a LiveKit room, all audio is routed to the system speaker even though a bluetooth headset is connected.

**To Reproduce**

1. Connect AirPods to Pixel 6a.
2. Play a YouTube video and confirm that audio is coming through AirPods.
3. Join a LiveKit room using sample app.
4. Notice that LiveKit audio is coming through speaker instead of AirPods.
5. Switch back to YouTube and now notice that audio from YouTube is also coming through speaker.
6. Leave LiveKit room.
7. Switch back to YouTube again and now notice that audio is coming through AirPods once again.

**Expected behavior**

In steps 4 and 5 above, audio should be routed to the AirPods and not the system speakers. This does not repro on iOS. On iOS, all audio is routed to the AirPods, as expected.

**Screenshots**

**Device Info:**

 - Device: Pixel 6a
 - OS: Android 13

**Dependencies Info (please reference your package-lock.json or yarn.lock file):**

 - livekit-react-native: 4f29ade31a5a32462beea51b060a8e5e266a4b25
 - livekit-client: [e.g. 1.6.0]
 - react-native-webrtc: [e.g. 106.0.0]

**Additional context**

**Comment by davidliu** [comment]
Would you happen to have the BLUETOOTH_CONNECT permission added to your android app's `AndroidManifest.xml` file?

**Comment by donaldkwong** [comment]
I'm using the example app in the RN SDK to repro this and that app doesn't have that permission in the manifest. I added it [here](https://github.com/livekit/client-sdk-react-native/blob/4a6591419b3aaa6e04a629cc9cc7732e431c33fa/example/android/app/src/main/AndroidManifest.xml) to test, but the problem still remains.

**Comment by donaldkwong** [comment]
Looks like the combination of adding this permission to the manifest and then explicitly granting `Nearby devices` permission to the app fixes this. Is this a requirement just to have audio routed through what the system audio output is set to?

**Comment by donaldkwong** [comment]
Can this be accomplished without granting this permission? I'm concerned that users may not always want to grant this permission (it's not really clear to the user why this permission is needed) and end up with a poor experience.

**Comment by davidliu** [comment]
For direct control (explicitly switching between speaker vs Bluetooth), I think it's needed last time I checked. It looks like it can be default routed through system without the permission, but I remember there were some issues on Android why we went this route. Will need to recheck this.

**Comment by davidliu** [comment]
Looks like this is a particular issue with the [library](https://github.com/twilio/audioswitch) we're using to handle audio output. It can be done without the permission, but it'll take some time; might need to do a rewrite to handle this without the permission.

**Comment by davidliu** [comment]
Fixed by #39.
