### ISSUE TITLE
unable to connect to room

### ISSUE THREAD

**Issue by kmamtora** [livekit/client-sdk-react-native#44]
here are the logs

 LOG  rn-webrtc:pc:DEBUG 7 setRemoteDescription OK +29ms
 LOG  rn-webrtc:pc:DEBUG 7 addIceCandidate +1ms
 LOG  rn-webrtc:pc:DEBUG 7 addIceCandidate +1ms
 LOG  rn-webrtc:pc:DEBUG 7 createAnswer +2ms
 LOG  rn-webrtc:pc:DEBUG 7 createAnswer OK +18ms
 LOG  rn-webrtc:pc:DEBUG 7 setLocalDescription +5ms
 LOG  rn-webrtc:pc:DEBUG 7 setLocalDescription OK +23ms
 LOG  rn-webrtc:pc:DEBUG 7 getStats +238ms
 LOG  Failed to connect

`import {Room} from 'livekit-client';
import {useParticipant, useRoom} from '@livekit/react-native';
import * as React from 'react';
import {useEffect, useState} from 'react';
import {
  ActivityIndicator,
  FlatList,
  StyleSheet,
  Text,
  View,
} from 'react-native';

import {ParticipantView} from './ParticipantView';
import {RoomControls} from './RoomControls';

const LIVEKET_SERVER_URL = 'ws://192.168.1.18:7880';
const TOKEN_SERVER_URL = 'http://192.168.1.18:7880/create-room-access-token';

export const RoomPage = ({navigation, route}) => {
  const [, setIsConnected] = useState(false);
  const [room] = useState(
    () =>
      new Room({
        publishDefaults: {simulcast: false},
        adaptiveStream: true,
      }),
  );
  const {participants} = useRoom(room);
  const {userName, roomName} = route.params;
  const [token, setToken] = useState('eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MTEwMTgyMzgsImlzcyI6IkFQSW5KeXZTTHU2eG9pVSIsImp0aSI6InRvbnlfc3RhcmsiLCJuYW1lIjoiVG9ueSBTdGFyayIsIm5iZiI6MTY3NTAxODIzOCwic3ViIjoidG9ueV9zdGFyayIsInZpZGVvIjp7InJvb20iOiJzdGFyay10b3dlciIsInJvb21Kb2luIjp0cnVlfX0.8fsusnNXIy1AJUOeZ8ffo5jSv5mh-HM81gPixRJU0CY');

  useEffect(() => {
    const fn = async () => {
      const body = JSON.stringify({
        identity: userName,
        name: userName,
        room: roomName,
        ttl: '1d',
      });

      console.log(body)

      const res = await fetch(TOKEN_SERVER_URL, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: body,
      });
      console.log(res)

      // const data = await res.json();
      // setToken(data.data.token);
    };
    fn();
  }, [userName, roomName]);

  useEffect(() => {
    if (token) {
      console.log('Connecting to ROOM....');
      room
        .connect(LIVEKET_SERVER_URL, token, {})
        .then(r => {
          if (!r) {
            console.log('Failed to connect');
            return;
          }
          console.log('Connected');
          setIsConnected(true);
        })
        .catch(err => {
          console.error('Error Connecting to Room', err);
        });

      return () => {
        room.disconnect();
      };
    } else {
      console.log('NO TOKEN WHILE ROOM CONNECTION');
    }
  }, [token, room]);

  const renderParticipant = ({item}) => {
    return (
      <ParticipantView participant={item} style={styles.otherParticipantView} />
    );
  };

  const {cameraPublication, microphonePublication} = useParticipant(
    room.localParticipant,
  );

  function isTrackEnabled(data) {
    return !(data?.isMuted ?? true);
  }

  if (participants.length && participants[0].identity) {
    return (
      <View style={styles.container}>
        <ParticipantView participant={participants[0]} style={styles.stage} />

        <FlatList
          data={participants}
          renderItem={renderParticipant}
          keyExtractor={item => item.sid}
          horizontal={true}
          style={styles.otherParticipantsList}
        />

        <RoomControls
          micEnabled={isTrackEnabled(microphonePublication)}
          setMicEnabled={enabled => {
            room.localParticipant.setMicrophoneEnabled(enabled);
          }}
          cameraEnabled={isTrackEnabled(cameraPublication)}
          setCameraEnabled={enabled => {
            room.localParticipant.setCameraEnabled(enabled);
          }}
          onDisconnectClick={() => {
            navigation.pop();
          }}
        />
      </View>
    );
  } else {
    return (
      <View style={styles.container}>
        <ActivityIndicator size="large" color="white" />
        <Text style={styles.text}>Loading...</Text>
      </View>
    );
  }
};

const styles = StyleSheet.create({
  container: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  stage: {
    flex: 1,
    width: '100%',
  },
  otherParticipantsList: {
    width: '100%',
    height: 150,
    flexGrow: 0,
  },
  otherParticipantView: {
    width: 150,
    height: 150,
  },
  text: {
    color: 'white',
  },
});`

**Comment by kmamtora** [comment]
Resolved my issue,

**Comment by Mihai-github** [comment]
what was the issue, i cannot make it work .... my .connect promise gets rejected every time

**Comment by davidliu** [comment]
What error do you get in the logs/promise?

**Comment by Mihai-github** [comment]
I've solved the issue, it seemed like I had a package missing and the room.connect: Promise kept getting rejected because of this.

**Comment by ciaoamigoschat** [comment]
Hi, I also have the same problem, may I know how you solved it?
