### ISSUE TITLE
Connectivity issues on dual-sim devices

### ISSUE THREAD

**Issue by davidzhao** [livekit/client-sdk-react-native#47]
**Describe the bug**

A user has reported being unable to connect to LiveKit using RN SDK from dual SIM devices when on cellular. The issue goes away when they switch to WiFi or takes out one of the SIM cards.

Livekit Cloud
livekit-react-native: 5ccd65b
livekit-client: 1.6.0
react-native-webrtc: 106.0.0

**Comment by lucienbl** [comment]
Hello,

We are also facing a similar issue. Not sure if this is related to this package or livekit-server, neither if it is a dual-sim issue or not (I do have dual-sim), but we are also unable to connect to the livekit server using cellular.

If there's anything new on this issue or any tips how to resolve this we'd be glad to hear 😁

Best regards,
Lucien

**Comment by sruli** [comment]
@lucienbl with help from the Livekit team, I solved this by adding this code to AppDelegate.m

```
#import <WebRTC/RTCFieldTrials.h>

- (BOOL)application:(UIApplication *)application
    didFinishLaunchingWithOptions:(NSDictionary *)launchOptions {
  NSDictionary *fieldTrials = @{kRTCFieldTrialUseNWPathMonitor : kRTCFieldTrialEnabledValue};
  RTCInitFieldTrialDictionary(fieldTrials);
  /* ... */
}
```

**Comment by lucienbl** [comment]
Thank you @sruli for the hint, it looks like my issue finally wasn't related to this, as setting up the TURN server resolved this on my end. But I'll keep this code part in my mind if it turns out I also have issues with dual SIM devices :)
