### ISSUE TITLE
peer connection is null when other participant connected

### ISSUE THREAD

**Issue by prabodh-syntizen** [livekit/client-sdk-react-native#48]
Able to connect room but when other participant is joining its giving 
unpublishing track
rn-webrtc:pc:DEBUG 0 createOffer +120ms
 LOG  rn-webrtc:pc:DEBUG 0 createOffer ERROR +4ms
 WARN  Possible Unhandled Promise Rejection (id: 0):
"peerConnection is null"

working on web properly but not in react native android

1)connecting calling token api
2)connected to room
3)when other participant try to join its giving above error

 "react": "18.2.0",
  "react-native": "0.71.2",
"@livekit/react-native": "^0.3.0",
 "livekit-client": "^1.3.2",
"react-native-webrtc": "106.0.0",

**Comment by davidliu** [comment]
Can you try upgrading the react-native-webrtc to latest?

**Comment by prabodh-syntizen** [comment]
I have tried with latest version also same is happening

**Comment by davidliu** [comment]
Can you post full logs from logcat when this happens?

**Comment by prabodh-syntizen** [comment]
<img width="967" alt="Screenshot 2023-03-04 at 8 43 28 PM" src="https://user-images.githubusercontent.com/121945063/222914107-aa25fc18-d2bf-4e5b-bd2f-78df882c6df8.png">

**Comment by prabodh-syntizen** [comment]
<img width="958" alt="Screenshot 2023-03-04 at 8 42 35 PM" src="https://user-images.githubusercontent.com/121945063/222914122-0666a64d-cd76-43f6-a169-175a5014b92c.png">

**Comment by prabodh-syntizen** [comment]
![Screenshot_1677942831](https://user-images.githubusercontent.com/121945063/222914127-677e376d-77ba-4ebf-9ecd-4375bc45f9c2.png)

**Comment by davidliu** [comment]
Are you using `react-native log-android` here or `adb logcat`? The react-native logging only outputs the JS console logs, so it'd be helpful if you could run `adb logcat` and output those logs.

Also, please copy paste those to a text file rather than screenshotting.

**Comment by prabodh-syntizen** [comment]
[adblogs.zip](https://github.com/livekit/client-sdk-react-native/files/10890981/adblogs.zip)

**Comment by prabodh-syntizen** [comment]
this is the complete adb logs

**Comment by davidliu** [comment]
Sorry, one last request, what version of `livekit-client` are you using? You can find what version is resolved in your `package-lock.json` or `yarn.lock` file.

**Comment by prabodh-syntizen** [comment]
livekit-client@^1.3.2, livekit-client@^1.6.0:
  version "1.6.5"
  resolved "https://registry.npmjs.org/livekit-client/-/livekit-client-1.6.5.tgz"
  integrity sha512-UDGSvmPW3gQnvbkFFpfDx0lIlTtp4tUv7HynIb8oT4JbVvvkGMaqMJ3vjxrz0EciasZZsbMAayMMwNnkPh2Pjw==
  dependencies:
    async-await-queue "^1.2.1"
    events "^3.3.0"
    loglevel "^1.8.0"
    protobufjs "^7.0.0"
    sdp-transform "^2.14.1"
    ts-debounce "^4.0.0"
    typed-emitter "^2.1.0"
    ua-parser-js "^1.0.2"
    webrtc-adapter "^8.1.1"
    
    
    this is showing  in package-lock.json

**Comment by prabodh-syntizen** [comment]
any update on this?

**Comment by Vaib215** [comment]
did you happen to solve this issue by yourself? We are also facing this issue in our application
