### ISSUE TITLE
error import type { AudioConfiguration } from './audio/AudioSession';

### ISSUE THREAD

**Issue by chanphiromsok** [livekit/client-sdk-react-native#49]
**Describe the bug**

![Screen Shot 2023-03-06 at 1 24 18 PM](https://user-images.githubusercontent.com/65760336/223034726-ecbaf525-8ff9-4f56-be2b-817fa4380efb.png)

**To Reproduce**
yarn add @livekit/react-native
 launch the app error 

**Device Info:**
 - Device: Oppo
 - Version 10

**Dependencies Info (please reference your package-lock.json or yarn.lock file):**

 - @livekit/react-native: ^3.0.0
 - livekit-client: 1.6.0
 - react-native-webrtc: ^106.0.6
 
 
** devDepencies
```
"devDependencies": {
        "@babel/core": "^7.12.9",
        "@babel/runtime": "^7.12.5",
        "@react-native-community/eslint-config": "^3.0.0",
        "@types/color": "^3.0.0",
        "@types/i18n-js": "^3.0.1",
        "@types/jest": "^24.0.18",
        "@types/lodash": "^4.14.172",
        "@types/mapbox__polyline": "^1.0.2",
        "@types/react": "^17.0.21",
        "@types/react-native": "^0.65.0",
        "@types/react-native-autocomplete-input": "^5.0.0",
        "@types/react-native-snap-carousel": "^3.8.4",
        "@types/react-native-status-bar-height": "^2.3.0",
        "@types/react-native-vector-icons": "^6.4.8",
        "@types/react-native-video": "^5.0.3",
        "@types/react-redux": "^7.1.4",
        "@types/react-test-renderer": "^16.9.0",
        "@types/redux-logger": "^3.0.7",
        "@types/websocket": "^1.0.0",
        "@types/yup": "^0.26.24",
        "@typescript-eslint/eslint-plugin": "^5.51.0",
        "@typescript-eslint/parser": "^5.51.0",
        "babel-jest": "^26.6.3",
        "babel-plugin-transform-remove-console": "^6.9.4",
        "metro-react-native-babel-preset": "^0.66.0",
        "ts-jest": "^24.0.0",
        "typescript": "^4.6.3"
    }
```

if I updated the code remove import type just import then work fine

**Comment by davidliu** [comment]
The error log is cut off. Please copy paste the logs rather than screenshotting.

**Comment by chanphiromsok** [comment]
> The error log is cut off. Please copy paste the logs rather than screenshotting.

How I don't see errors anymore maybe my project is too old now it can close
