### ISSUE TITLE
Microphone requested and by default enabled for viewer or listener

### ISSUE THREAD

**Issue by b0iq** [livekit/client-sdk-react-native#55]
**Describe the bug**

So I'm joining a room from my other phone as viewer who **cannot** publish and tracks. The problem is the viewer microphone enabled and used all the time!

**To Reproduce**
1. Create new room 
2. Join as a host (Live Streaming)
3. Then join as viewer

**Expected behavior**

The viewer microphone shall not be requested or enabled if he is not going to publish any thing

**Screenshots**

**Viewer's Screenshot**
![Screenshot 2023-04-12 at 00 09 08](https://user-images.githubusercontent.com/106549013/231277362-8d6a223b-dd20-42c0-8aa6-e8f789335888.jpeg)
publisher's Screenshot
![IMG_8CE62FB51764-1](https://user-images.githubusercontent.com/106549013/231278604-09542617-f55b-46c9-9cd8-a95fe8eab1a3.jpeg)

**Device Info:**

Viewer: iPhone 11 [16.1.2]
Host: iPhone 14 [16.4.1]

**Dependencies Info (please reference your package-lock.json or yarn.lock file):**

 - @livekit/react-native: ^0.3.0
 - livekit-client: ^1.7.1
 - react-native-webrtc: ^111.0.0

**Comment by b0iq** [comment]
Update: 

Reproduce demo: https://github.com/b0iq/LKExample/

**Comment by davidliu** [comment]
Using your demo, microphone isn't requested or published when joining as a viewer, only when joining as a publisher.

**Comment by b0iq** [comment]
Here’s the permission access for a phone that **never** joined as publisher 
iOS 16.1.2
![IMG_5DB4D54D3114-1](https://user-images.githubusercontent.com/106549013/232473915-5d9d7d52-0680-46a8-b060-e03f17206f6a.jpeg)

And this is the server configs for generating token for viewer
```ts

   at.addGrant({
      roomJoin: true,
      room: 'roomId',
      roomList: false,
      canPublish: false,
      roomAdmin: false,
      canPublishData: false,
      canSubscribe: true,
    });

```

**Comment by davidliu** [comment]
Closing as stale.
