### ISSUE TITLE
Android 5.1 can't connect to a room

### ISSUE THREAD

**Issue by alefebspp** [livekit/client-sdk-react-native#61]
**Describe the bug**

A have a app that runs livekit. When connecting to the the app via emulator or phone with more recent androids, the app runs normaly. The problem is with android 5.1(which is needed to run with virtual reality goggles). The error showed by the app is : 
Error: Could not connect PeerConnection after timeout

EDIT:  If I change something in the code and save while I'm on the call screen, the app crashes with the following message: Unfortunately, app has stopped working.

EDIT2: Executing the react-native example with android 5.1 i had the same problem described on edit one, but instead of having to change the code to see the error i've got the error when trying to connect to a room.

**To Reproduce**

1. Try to connect to a room
2. See error

**Expected behavior**

Connect to a livekit room

**Screenshots**

![error](https://user-images.githubusercontent.com/106111153/233140403-208de8d8-d274-44cc-a65a-9f1935f017bc.PNG)

**Device Info:**

**Dependencies Info (please reference your package-lock.json or yarn.lock file):**

    "@livekit/react-native": "^0.3.0",
    "@react-native-community/async-storage": "^1.12.1",
    "@react-navigation/native": "^6.1.1",
    "@react-navigation/native-stack": "^6.9.7",
    "@tanstack/react-query": "^4.28.0",
    "@unform/core": "^2.1.6",
    "@unform/mobile": "^2.1.6",
    "axios": "^1.2.1",
    "date-fns": "^2.29.3",
    "livekit-client": "^1.7.0",
    "react": "18.1.0",
    "react-native": "0.70.6",
    "react-native-blob-util": "^0.17.3",
    "react-native-canvas": "^0.1.38",
    "react-native-device-info": "^10.4.0",
    "react-native-document-picker": "^8.2.0",
    "react-native-dotenv": "^3.4.8",
    "react-native-gesture-handler": "^2.8.0",
    "react-native-pdf": "^6.6.2",
    "react-native-render-html": "^6.3.4",
    "react-native-safe-area-context": "^4.4.1",
    "react-native-screens": "^3.20.0",
    "react-native-svg": "^13.8.0",
    "react-native-video": "^5.2.1",
    "react-native-video-controls": "^2.8.1",
    "react-native-webrtc": "^106.0.7",
    "react-native-webview": "^11.26.1",
    "socket.io-client": "^4.6.1",
    "styled-components": "^5.3.6"

**Additional context**

**Comment by davidliu** [comment]
Can you post logs from logcat when the error occurs?

**Comment by alefebspp** [comment]
This is when the app doesnt crash:
```
 Possible Unhandled Promise Rejection (id: 0):
Error: could not connect PeerConnection after timeout
Error: could not connect PeerConnection after timeout
    at construct (native)
    at apply (native)
    at _construct (http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.cmclima_app&modulesOnly=false&runModule=true:19811:28)
    at Wrapper (http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.cmclima_app&modulesOnly=false&runModule=true:19775:64)
    at construct (native)
    at _createSuperInternal (http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.cmclima_app&modulesOnly=false&runModule=true:150182:406)
    at call (native)
    at zn (http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.cmclima_app&modulesOnly=false&runModule=true:157489:30)
    at construct (native)
    at _createSuperInternal (http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.cmclima_app&modulesOnly=false&runModule=true:150182:406)
    at call (native)
    at Hn (http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.cmclima_app&modulesOnly=false&runModule=true:157500:31)
    at anonymous (http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.cmclima_app&modulesOnly=false&runModule=true:162747:124)
    at apply (native)
    at anonymous (http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.cmclima_app&modulesOnly=false&runModule=true:26322:26)
    at _callTimer (http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.cmclima_app&modulesOnly=false&runModule=true:26261:17)
    at callTimers (http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.cmclima_app&modulesOnly=false&runModule=true:26417:19)
    at apply (native)
    at __callFunction (http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.cmclima_app&modulesOnly=false&runModule=true:2434:36)
    at anonymous (http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.cmclima_app&modulesOnly=false&runModule=true:2196:31)
    at __guard (http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.cmclima_app&modulesOnly=false&runModule=true:2386:15)
    at callFunctionReturnFlushedQueue (http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.cmclima_app&modulesOnly=false&runModule=true:2195:21)
```

**Comment by alefebspp** [comment]
When the app crashed, there was no info at the log

**Comment by davidliu** [comment]
You need the grab logs from adb logcat, not just the metro logs.

**Comment by alefebspp** [comment]
PeerConnect error on logcat: 
W/ReactNativeJS( 5286): Possible Unhandled Promise Rejection (id: 0):
W/ReactNativeJS( 5286): Error: could not connect PeerConnection after timeout
W/ReactNativeJS( 5286): Error: could not connect PeerConnection after timeout
W/ReactNativeJS( 5286):     at construct (native)
W/ReactNativeJS( 5286):     at apply (native)
W/ReactNativeJS( 5286):     at _construct (http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.cmclima_app&modulesOnly=false&runModule=true:19811:28)
W/ReactNativeJS( 5286):     at Wrapper (http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.cmclima_app&modulesOnly=false&runModule=true:19775:64)
W/ReactNativeJS( 5286):     at construct (native)
W/ReactNativeJS( 5286):     at _createSuperInternal (http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.cmclima_app&modulesOnly=false&runModule=true:150182:406)
W/ReactNativeJS( 5286):     at call (native)
W/ReactNativeJS( 5286):     at zn (http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.cmclima_app&modulesOnly=false&runModule=true:157489:30)
W/ReactNativeJS( 5286):     at construct (native)
W/ReactNativeJS( 5286):     at _createSuperInternal (http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.cmclima_app&modulesOnly=false&runModule=true:150182:406)
W/ReactNativeJS( 5286):     at call (native)
W/ReactNativeJS( 5286):     at Hn (http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.cmclima_app&modulesOnly=false&runModule=true:157500:31)
W/ReactNativeJS( 5286):     at anonymous (http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.cmclima_app&modulesOnly=false&runModule=true:162747:124)
W/ReactNativeJS( 5286):     at apply (native)
W/ReactNativeJS( 5286):     at anonymous (http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.cmclima_app&modulesOnly=false&runModule=true:26322:26)
W/ReactNativeJS( 5286):     at _callTimer (http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.cmclima_app&modulesOnly=false&runModule=true:26261:17)
W/ReactNativeJS( 5286):     at callTimers (http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.cmclima_app&modulesOnly=false&runModule=true:26417:19)
W/ReactNativeJS( 5286):     at apply (native)
W/ReactNativeJS( 5286):     at __callFunction (http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.cmclima_app&modulesOnly=false&runModule=true:2434:36)
W/ReactNativeJS( 5286):     at anonymous (http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.cmclima_app&modulesOnly=false&runModule=true:2196:31)
W/ReactNativeJS( 5286):     at __guard (http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.cmclima_app&modulesOnly=false&runModule=true:2386:15)
W/ReactNativeJS( 5286):     at callFunctionReturnFlushedQueue (http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.cmclima_app&modulesOnly=false&runModule=true:2195:21)
E/eglCodecCommon( 5286): glUtilsParamSize: unknow param 0x000085b5
E/eglCodecCommon( 5286): glUtilsParamSize: unknow param 0x000085b5
E/eglCodecCommon( 5286): glUtilsParamSize: unknow param 0x000085b5
E/eglCodecCommon( 5286): glUtilsParamSize: unknow param 0x000085b5
E/eglCodecCommon( 5286): glUtilsParamSize: unknow param 0x000085b5
E/eglCodecCommon( 5286): glUtilsParamSize: unknow param 0x000085b5
E/eglCodecCommon( 5286): glUtilsParamSize: unknow param 0x000085b5
E/eglCodecCommon( 5286): glUtilsParamSize: unknow param 0x000085b5
E/eglCodecCommon( 5286): glUtilsParamSize: unknow param 0x000085b5
E/eglCodecCommon( 5286): glUtilsParamSize: unknow param 0x000085b5
E/eglCodecCommon( 5286): glUtilsParamSize: unknow param 0x000085b5
E/eglCodecCommon( 5286): glUtilsParamSize: unknow param 0x000085b5
E/eglCodecCommon( 5286): glUtilsParamSize: unknow param 0x000085b5
E/eglCodecCommon( 5286): glUtilsParamSize: unknow param 0x000085b5
E/eglCodecCommon( 5286): glUtilsParamSize: unknow param 0x000085b5
E/eglCodecCommon( 5286): glUtilsParamSize: unknow param 0x000085b5
E/eglCodecCommon( 5286): glUtilsParamSize: unknow param 0x000085b5
E/eglCodecCommon( 5286): glUtilsParamSize: unknow param 0x000085b5
E/eglCodecCommon( 5286): glUtilsParamSize: unknow param 0x000085b5
E/eglCodecCommon( 5286): glUtilsParamSize: unknow param 0x000085b5
D/EGL_emulation( 1718): eglMakeCurrent: 0x7f14dc0e0380: ver 2 0 (tinfo 0x7f14dc173280)

**Comment by alefebspp** [comment]
When app crashed: 
```
E/AndroidRuntime( 5286): FATAL EXCEPTION: pool-7-thread-1
E/AndroidRuntime( 5286): Process: com.cmclima_app, PID: 5286
E/AndroidRuntime( 5286): java.lang.NoClassDefFoundError: com.oney.WebRTCModule.SerializeUtils$$ExternalSyntheticLambda2
E/AndroidRuntime( 5286):        at com.oney.WebRTCModule.SerializeUtils.serializeRtpParameters(SerializeUtils.java:133)
E/AndroidRuntime( 5286):        at com.oney.WebRTCModule.SerializeUtils.serializeReceiver(SerializeUtils.java:100)
E/AndroidRuntime( 5286):        at com.oney.WebRTCModule.PeerConnectionObserver.lambda$onAddTrack$9$com-oney-WebRTCModule-PeerConnectionObserver(PeerConnectionObserver.java:566)
E/AndroidRuntime( 5286):        at com.oney.WebRTCModule.PeerConnectionObserver$$ExternalSyntheticLambda9.run(D8$$SyntheticClass)E/AndroidRuntime( 5286):        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
E/AndroidRuntime( 5286):        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
E/AndroidRuntime( 5286):        at java.lang.Thread.run(Thread.java:818)
W/ActivityManager( 1575):   Force finishing activity 1 com.cmclima_app/.MainActivity
D/gralloc_ranchu( 1166): gralloc_alloc: Creating ashmem region of size 589824
D/com.oney.WebRTCModule.VideoTrackAdapter( 5286): Created adapter for TR_VCVJqG837iwynY
D/        ( 1575): HostConnection::get() New Host Connection established 0x7f14d040d740, tid 3262
I/art     ( 5286): Rejecting re-init on previously-failed class java.lang.Class<com.oney.WebRTCModule.SerializeUtils$$ExternalSyntheticLambda2>
E/EGL_emulation( 1166): tid 1166: eglCreateSyncKHR(1881): error 0x3004 (EGL_BAD_ATTRIBUTE)
I/Process ( 5286): Sending signal. PID: 5286 SIG: 9
E/lowmemorykiller( 1163): Error writing /proc/5286/oom_score_adj; errno=22
D/ConnectivityService( 1575): ConnectivityService NetworkRequestInfo binderDied(NetworkRequest [ id=8, legacyType=-1, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED&NOT_VPN] ], android.os.BinderProxy@2f21308)
I/WindowState( 1575): WIN DEATH: Window{3378f8da u0 com.cmclima_app/com.cmclima_app.MainActivity}
D/ConnectivityService( 1575): releasing NetworkRequest NetworkRequest [ id=8, legacyType=-1, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED&NOT_VPN] ]
E/ConnectivityService( 1575): RemoteException caught trying to send a callback msg for NetworkRequest [ id=8, legacyType=-1, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED&NOT_VPN] ]
I/ActivityManager( 1575): Process com.cmclima_app (pid 5286) has died
D/gralloc_ranchu( 1166): gralloc_alloc: Creating ashmem region of size 3932160
E/EGL_emulation( 1166): tid 1166: eglCreateSyncKHR(1881): error 0x3004 (EGL_BAD_ATTRIBUTE)
I/ActivityManager( 1575): Config changes=480 {1.0 310mcc260mnc en_US ?layoutDir sw384dp w384dp h567dp 320dpi nrml port finger -keyb/v/h dpad/v s.10}
V/ActivityManager( 1575): Display changed displayId=0
I/InputReader( 1575): Reconfiguring input devices.  changes=0x00000004
I/InputReader( 1575): Device reconfigured: id=0, name='qwerty2', size 768x1280, orientation 0, mode 1, display id 0
W/SocketClient( 1171): write error (Broken pipe)
W/DnsProxyListener( 1171): Error writing DNS result to client
W/SocketClient( 1171): write error (Broken pipe)
W/DnsProxyListener( 1171): Error writing DNS result to client
D/EGL_emulation( 1718): eglMakeCurrent: 0x7f14dc0e0380: ver 2 0 (tinfo 0x7f14dc173280)
I/OpenGLRenderer( 1575): Initialized EGL, version 1.4
D/EGL_emulation( 1575): eglCreateContext: 0x7f14dc0d9880: maj 2 min 0 rcv 2
D/EGL_emulation( 1575): eglMakeCurrent: 0x7f14dc0d9880: ver 2 0 (tinfo 0x7f14dc15d6a0)
D/EGL_emulation( 1909): eglMakeCurrent: 0xee9d1160: ver 2 0 (tinfo 0xee839550)
D/EGL_emulation( 1718): eglMakeCurrent: 0x7f14dc0e0380: ver 2 0 (tinfo 0x7f14dc173280)
D/EGL_emulation( 1575): eglMakeCurrent: 0x7f14dc0d9880: ver 2 0 (tinfo 0x7f14dc15d6a0)
D/EGL_emulation( 1575): eglMakeCurrent: 0x7f14dc0d9880: ver 2 0 (tinfo 0x7f14dc15d6a0)
D/EGL_emulation( 1718): eglMakeCurrent: 0x7f14dc0e0380: ver 2 0 (tinfo 0x7f14dc173280)
W/InputMethodManagerService( 1575): Got RemoteException sending setActive(false) notification to pid 5286 uid 10060
D/EGL_emulation( 1718): eglMakeCurrent: 0x7f14dc0e0380: ver 2 0 (tinfo 0x7f14dc173280)
I/WindowManager( 1575): Screen frozen for +306ms due to Window{d98482e u0 NavigationBar}
I/Icing   ( 2663): IndexChimeraService.getServiceInterface callingPackage=com.google.android.googlequicksearchbox componentName=null serviceId=21
D/EGL_emulation( 1718): eglMakeCurrent: 0x7f14dc0e0380: ver 2 0 (tinfo 0x7f14dc173280)
W/Icing   ( 2663): No valid account for uploading user actions
D/EGL_emulation( 1718): eglMakeCurrent: 0x7f14dc0e0380: ver 2 0 (tinfo 0x7f14dc173280)
I/Icing   ( 2663): Usage reports ok 0, Failed Usage reports 0, indexed 0, rejected 0
I/Icing   ( 2663): IndexChimeraService.getServiceInterface callingPackage=com.google.android.gms componentName=null serviceId=30 
W/Icing   ( 2663): No valid account for uploading user actions
I/Icing   ( 2663): Usage reports ok 0, Failed Usage reports 0, indexed 0, rejected 0
D/EGL_emulation( 1909): eglMakeCurrent: 0xee9d1160: ver 2 0 (tinfo 0xee839550)
D/EGL_emulation( 1909): eglMakeCurrent: 0xee9d1160: ver 2 0 (tinfo 0xee839550)
D/EGL_emulation( 1909): eglMakeCurrent: 0xee9d1160: ver 2 0 (tinfo 0xee839550)
W/OpenGLRenderer( 1909): Incorrectly called buildLayer on View: aep, destroying layer...
D/EGL_emulation( 1909): eglMakeCurrent: 0xee9d1160: ver 2 0 (tinfo 0xee839550)
I/art     ( 1575): Explicit concurrent mark sweep GC freed 10693(575KB) AllocSpace objects, 2(592KB) LOS objects, 29% free, 9MB/13MB, paused 496us total 11.329ms
```

**Comment by alefebspp** [comment]
A different type of log was printed when the app crashes: 
```
FATAL EXCEPTION: main
Process: com.cmclima_app, PID: 12216
java.lang.NoClassDefFoundError: com.twilio.audioswitch.scanners.AudioDeviceScanner
	at com.twilio.audioswitch.AudioSwitch.<init>(AudioSwitch.kt:87)
	at com.twilio.audioswitch.AudioSwitch.<init>(AudioSwitch.kt:53)
	at com.livekit.reactnative.audio.AudioSwitchManager.lambda$start$2$com-livekit-reactnative-audio-AudioSwitchManager(AudioSwitchManager.java:61)
	at com.livekit.reactnative.audio.AudioSwitchManager$$ExternalSyntheticLambda1.run(D8$$SyntheticClass)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5254)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
```

**Comment by davidliu** [comment]
Looks like react-native-webrtc is incompatible with API 23 and lower.

https://github.com/react-native-webrtc/react-native-webrtc/issues/1291

Closing this since we can't fix this.
