### ISSUE TITLE
iOS: Video stream does not resume when app is brought back into the foreground

### ISSUE THREAD

**Issue by jbrowning** [livekit/client-sdk-react-native#63]
**Describe the bug**

When a video call is in progress, the video stream for a participant on iOS will freeze for other participants if the app is backgrounded. When the iOS user brings the app back into the foreground, the video stream does not resume and remains frozen for the all other participants. The local monitor stream for the user on iOS will continue to work as expected and audio is not interrupted at any time. There are also no track/participant/room events indicating that anything is interrupted nor are there any relevant log entries at the `debug` level.

**To Reproduce**

1. Connect to a room in the Example app
2. Wait for another user to connect
3. Put the app into the background on a device running iOS
4. Bring the app back into the foreground
5. The other participants will still see frozen video from the iOS user

**Expected behavior**

For the video stream to show as unavailable when the app is backgrounded (if it is not possible to remain streaming on iOS) and to resume streaming when the app is placed back into the foreground.

**Screenshots**

N/A

**Device Info:**

- Device: iPhone 6s Plus, iPhone 14 Pro
- OS: iOS 15.7.4, iOS 16.4.1

**Dependencies Info (please reference your package-lock.json or yarn.lock file):**

- @livekit/react-native: 1.0.0
- livekit-client: 1.8.0
- react-native-webrtc: 111.0.0

This issue is NOT present with the following older dependencies:

- @livekit/react-native: github:livekit/client-sdk-react-native#5ccd65b01e4ea591e10dac6cd2334d2ff6b60e34
- livekit-client: 1.6.0
- react-native-webrtc: 106.0.0

**Comment by davidliu** [comment]
Hmm, looks like something on the react-native-webrtc side when upgrading to m111, will investigate further.

**Comment by davidliu** [comment]
Unfortunately, seems like it might be a while before we can get this working properly. For now, I think you should be able to handle this manually listening to the [AppState](https://reactnative.dev/docs/appstate) and disabling the camera when it goes into the background.

**Comment by jbrowning** [comment]
@davidliu Any update on this? Looks like that workaround is not working as expected in testing with `@livekit/react-native 1.0.1` and `react-native-webrtc 111.0.1`. After toggling the camera back on, the video goes to black instead of resuming for both iOS and Android participants.

**Comment by davidliu** [comment]
Hmm, how are you handling this? This is what I have and seems to work for me:


    const appState = React.useRef(AppState.currentState);
    const [appStateVisible, setAppStateVisible] = useState(appState.current);
  
    useEffect(() => {
      const subscription = AppState.addEventListener('change', nextAppState => {
        if (
          appState.current.match(/inactive|background/) &&
          nextAppState === 'active'
        ) {
          console.log('App has come to the foreground!');
        }

        appState.current = nextAppState;
        setAppStateVisible(appState.current);
        console.log('AppState', appState.current);
      });

      return () => {
        subscription.remove();
      };
    }, []);

    useEffect(() => {
      if(room && isConnected){
        if(appStateVisible === 'active') {
          room.localParticipant.setCameraEnabled(true)
        } else {
          room.localParticipant.setCameraEnabled(false)
        }
      } 
    }, [room, isConnected, appStateVisible]);

**Comment by jbrowning** [comment]
@davidliu Thanks for the suggestion. I've done some more testing and found that this is not directly related to employing that workaround. Previously, when video did not resume after an iOS participant brought the app back into the foreground, toggling video off/on would resume the video stream so that is what I was planning on automating. Now, this action results in black screen for the other participants instead of the video coming back.

This is occurring on the RN example app as well as our own so I'm suspecting that there was a backend change that affected this.

I've tested on the following library versions and all behave the same:

* @livekit/react-native: 1.0.0 & 1.0.1
* react-native-webrtc: 111.0.0 & 111.0.1

I am on the LiveKit Community Slack if you'd like to continue the conversation there.

**Comment by davidliu** [comment]
We'll be releasing a forked version of react-native-webrtc soon that shouldn't have the original bug, so that'll remove the need for a workaround.

**Comment by davidliu** [comment]
Hey @jbrowning, try the latest 1.1.2 release. Note that there are few new setup steps involved that can be found in our README here:

https://github.com/livekit/client-sdk-react-native#installation
