### ISSUE TITLE
Participant does not have video track listed for other users even though it is published

### ISSUE THREAD

**Issue by alefebspp** [livekit/client-sdk-react-native#68]
**Describe the bug**

For some reason, some users (using mobile devices) do not have their video tracks displayed to other users. They can see their videos and other users' videos, but their video tracks are not displayed to others. Their audio tracks are listed correctly. What could be the cause of this? The publication of the participant's video track is not recognized in the room's event, only the publication of the audio track

**To Reproduce**

**Expected behavior**

**Screenshots**

**Device Info:**

**Dependencies Info (please reference your package-lock.json or yarn.lock file):**

 - @livekit/react-native: [e.g. commit hash]
 - livekit-client: [e.g. 1.6.0]
 - react-native-webrtc: [e.g. 106.0.0]

**Additional context**

**Comment by davidliu** [comment]
What are the options being passed when creating the `Room` object?

**Comment by alefebspp** [comment]
We handle the room connection on a useEffect:   
```
useEffect(() => {
    room.connect(url, token, {}).then(async () => {
      AudioSession.configureAudio({
        android: { preferredOutputList: ['speaker', 'earpiece', 'headset'] },
        ios: { defaultOutput: 'speaker' },
      });
      AudioSession.startAudioSession();
      setIsMicMuted(false);
      const devices = await Room.getLocalDevices('videoinput');
      if (room.options.videoCaptureDefaults) {
        room.options.videoCaptureDefaults.deviceId = devices[0].deviceId;
      }
      room.localParticipant.setCameraEnabled(true);
      socket.emit('room_connect', { call_id: callId });
    });
    return () => {
      room.disconnect();
      AudioSession.stopAudioSession();
    };
  }, [room, url, token]);
```

**Comment by davidliu** [comment]
What about when creating the `Room` object itself?

**Comment by davidliu** [comment]
Also, is the video track viewable locally?

**Comment by alefebspp** [comment]
Yes, the user can see his video locally. This is the room object: 
`const [room] = useState(() => new Room());`

**Comment by davidliu** [comment]
Can you try turning off simulcast like so?

```
new Room({
  publishDefaults: { 
    simulcast: false,
  }
})
```

**Comment by alefebspp** [comment]
Yes, i'm going try it out

**Comment by alefebspp** [comment]
I know this question has nothing to do with the discussion, but if it can be answered here, great. I'm using the updateSubscription room service. I noticed that the track's sid gets undefined after the first use of the service and I get this error from livekit: `data: { code: 'malformed', msg: 'the json request could not be decoded' }`. Do you have any idea why the sid is getting undefined after the first use of the updateSubuscriptions service?

**Comment by alefebspp** [comment]
Turning simulcast to false solved the problem. What impact would it have on the video with the simulcast option disabled?

**Comment by alefebspp** [comment]
About the updateSubscription service, I think it's better to open a new topic explaining the problem better. Anyway, thanks for taking the time to respond.

**Comment by alefebspp** [comment]
Another question: why did this problem only happen with some mobile devices? Any idea?

**Comment by davidliu** [comment]
There's currently an issue with simulcast on the webrtc sdk we're using. Will be releasing a new version in the next couple days that should fix this issue.

**Comment by alefebspp** [comment]
Ok! Thank you.

**Comment by alefebspp** [comment]
@davidliu Is there a way to dynamically enable or disable simulcast during room connection? I would like to address this for users who are having the issue cited in the discussion

**Comment by davidliu** [comment]
Hey @alefebspp, try the new 1.1.2 release. This should fix the simulcast issues you're seeing. Note that there are a few new setup changes required that can be found in our README here:

https://github.com/livekit/client-sdk-react-native#installation
