### ISSUE TITLE
Sound issues

### ISSUE THREAD

**Issue by JenyaIII** [livekit/client-sdk-react-native#7]
Sound is not played from the main speaker. The sound is played from the speaker above the screen. How change audio output ?

**Comment by nextriot** [comment]
@JenyaIII were you able to get this working across devices and having new participants show up in a connected room? Would you mind sharing your code if so, or weighing in on my [issue](https://github.com/livekit/client-sdk-react-native/issues/8) if possible?

**Comment by JenyaIII** [comment]
@nextriot I took the code from the example. Just moved the call methods to the mobx model. My users don't connect the first time either. But I have another error, the server connection timeout expires.

**Comment by davidliu** [comment]
Closing this to consolidate with #15.
