### ISSUE TITLE
[livekit/react-native-webrtc]  git library history big objects remove

### ISSUE THREAD

**Issue by zesun96** [livekit/client-sdk-react-native#79]
The react-native-webrtc library so large , because of webrtc library history。
[livekit/react-native-webrtc] is a fork，I cannot put issues， so i write there。

this is git bash out:
$ git rev-list --objects --all | grep "$(git verify-pack -v .git/objects/pack/*.idx | sort -k 3 -n | tail -5 | awk '{print$1}')"
a08059db5ed179e118b3517a7f2b756f886ec2b7 ios/WebRTC.framework/WebRTC
c15c0df402d0fd94d5725be4fc7380e09769604b ios/WebRTC.framework/WebRTC
46d395efa2e2ceab9c2057fd14da9bf2d6c1530b ios/WebRTC.framework/WebRTC
145102ef6cb1f51ac7d4b4f565a796445135347e ios/WebRTC.framework/WebRTC
dce70a686b0394b7aa767726f7bd73ef89fb964d ios/libjingle_peerconnection/libWebRTC.a

**Comment by davidzhao** [comment]
It would be good to rewrite history after moving these files to LFS.

**Comment by zesun96** [comment]
oh，It is so bad that I don't have LFS，so I delete them directly。

**Comment by zesun96** [comment]
I run it,  ".git" folder [ 419 MB ==> 29.5 MB]
