### ISSUE TITLE
expo is not working in version "@livekit/react-native": "^1.1.2" but works in ^1.0.0

### ISSUE THREAD

**Issue by yareyaredesuyo** [livekit/client-sdk-react-native#80]
**Describe the bug**

This library does not work with Expo if the version is ^1.1.2.

- I investigated the reason and found it works in following repository and uses version ^1.0.0
  - https://github.com/qweasd1/livekit-webrtc-expo-sample/tree/main  

**To Reproduce**

1. follow these instruction  https://github.com/livekit/client-sdk-react-native/wiki/Expo-Development-Build-Instructions
3. run `eas build --profile development --local` (iOS target)

**Expected behavior**

@livekit/react-native is available in expo in latest version

**Screenshots**

![Simulator Screenshot - iPhone 14 - 2023-06-29 at 17 56 51](https://github.com/livekit/client-sdk-react-native/assets/31843888/e00f2460-6d89-4c57-a9c4-3680a510b940)

<img width="847" alt="Screenshot 2023-06-29 at 17 57 01" src="https://github.com/livekit/client-sdk-react-native/assets/31843888/adfe77f3-776a-4237-90ed-1b57611ca09e">

**Device Info:**

 - Device: iPhone Simulator 14
 - OS: iOS17 (beta)

**Dependencies Info (please reference your package-lock.json or yarn.lock file):**

 - @livekit/react-native: ^1.1.2
 - react-native-webrtc: ^111.0.1

And this library looks like currently not work with @livekit/react-native-webrtc (expo environment)

got following error

```
[INSTALL_PODS] [!] The 'Pods-test' target has frameworks with conflicting names: webrtc.xcframework.
```

**Comment by zesun96** [comment]
@yareyaredesuyo 
please add `@livekit/react-native-webrtc` in your package.json.
you need to 'ios' dir to run `pod install`, or if you  mac is M1 , the `pod install` maybe fail, you can download webrtc lib, and move it on pod cache

**Comment by b0iq** [comment]
I'm working on Expo 49 (custom dev client) (iOS + Android) having no issue with it

**Comment by harlandjp** [comment]
`[INSTALL_PODS] [!] The 'Pods-test' target has frameworks with conflicting names: webrtc.xcframework.`

Having the same issue with Expo 48.

Is upgrading to Expo 49 a requirement?

**Comment by harlandjp** [comment]
```
[INSTALL_PODS] [!] The 'Pods-test' target has frameworks with conflicting names: webrtc.xcframework.
```

Had the same problem and removing `react-native-webrtc` from my package.json fixed it.

**Comment by davidliu** [comment]
Closing as obsolete. Works on most recent Expo versions now.
