### ISSUE TITLE
Can't see self camera picture on android app

### ISSUE THREAD

**Issue by zesun96** [livekit/client-sdk-react-native#82]
I add modules by
_yarn add @livekit/react-native @livekit/react-native-webrtc_

when the @livekit/react-native-webrtc version is 104.0.1, there is an error on opening camera.
**[Error: Exception in HostFunction: expected 0 arguments, got 1]**

I track the source of the error，because of **RTCRtpSender.getCapabilities(kind)**
open camera called it at 【RTCEngine.ts】- 【setPreferredCodec】https://github.com/livekit/client-sdk-js/blob/main/src/room/RTCEngine.ts#L609

@livekit/react-native-webrtc version 104.0.0 is ok.

I find RTCRtpSender.getCapabilities changed in [104.0.1](https://github.com/livekit/react-native-webrtc/commit/2c4d211bfdfe4018243c4db13efdcbbbad61cea0#diff-cf1b83a6ba37914e0f19fe4773cd0d71ad9deb81334f976d729ddba37a8f1e7f)

**Comment by davidliu** [comment]
What version of `livekit-client` is being used?

**Comment by zesun96** [comment]
@davidliu livekit-client@1.10.0

**Comment by davidzhao** [comment]
@zesun96 issue should no longer be there in the latest version. Please reopen if problem persists.
