### ISSUE TITLE
where is createDataChannel?

### ISSUE THREAD

**Issue by nreyes-qualabs** [livekit/client-sdk-react-native#83]
Good afternoon everyone, I hope you're all having a great day. I humbly come here today in search of some assistance regarding the understanding of some details when it comes to the inner workings of this library. More specifically about its use of `@livekit/react-native-webrtc`. I've been looking at said dependency and my current understanding is that, although it has some differences from the `react-native-webrtc` library that it was forked from, it should still be used by invoking the `RTCPeerConnection.createDataChannel` method, as it is suggested in the `BasicUsage.md` file that it's still present even in the fork:

```javascript
let datachannel = peerConnection.createDataChannel( 'my_channel' );

datachannel.addEventListener( 'open', event => {} );
datachannel.addEventListener( 'close', event => {} );
datachannel.addEventListener( 'message', message => {} );
```

But contraty to what I expected, there isn't any reference to `createDataChannel` anywhere in this project. How so? Is this method being used indirectly in some way that I'm unaware of?

I'd greatly appreciate any info on this matter.

Thanks a lot for your time! 

Cheers

**Comment by davidliu** [comment]
This library is a wrapper around `livekit-client` to make it compatible for react-native. The core code can be found here:

https://github.com/livekit/client-sdk-js

It creates data channels here:

https://github.com/livekit/client-sdk-js/blob/a8ed3477758ef13c97fe583d228976698a1be5ac/src/room/RTCEngine.ts#L522

**Comment by nreyes-qualabs** [comment]
@davidliu just a quick follow up, are data channels used exclusively for the chat, by any chance? (in the context of a Livekit room) or are they also used for the webrtc part? Thanks again for your answers!

**Comment by davidliu** [comment]
@nreyes-qualabs In terms of functionality that we provide on top of data channels, yes, they're exclusively used for chat at the moment, but it's also for consumers of the library to use however they wish. The data channels can be used to send any arbitrary information to other participants.

**Comment by nreyes-qualabs** [comment]
Can't thank you enough. Really helpful. Have a great weekend!
