### ISSUE TITLE
iOS doesn't respect videoCaptureDefaults?

### ISSUE THREAD

**Issue by mstrokin** [livekit/client-sdk-react-native#85]
**Describe the bug**

Setting the capture defaults to 720x540 works as expected on Android client, but on iOS client the resulting video is 640x480

**To Reproduce**

Set videoCaptureDefaults to use 720x540 :

videoCaptureDefaults: {
        resolution: new VideoPreset(720, 540, 300000, 25).resolution,
},

Then display the camera publication information:
{cameraPublication?.dimensions.width}x{cameraPublication?.dimensions.height}

Tested with both simulcast: true and simulcast:false

**Expected behavior**

iOS using same resolution as set in the config

**Device Info:**

 - Device: iPhone 8
 - OS: iOS 16.5

**Dependencies Info:**

 - @livekit/react-native: 1.1.2
 - livekit-client: 1.12.1
 - @livekit/react-native-webrtc: 104.0.1

**Comment by mstrokin** [comment]
Same issue with older version of @livekit/react-native with latest react-native-webrtc, am I doing something wrong?

**Comment by mstrokin** [comment]
Sorry, seems like we have to pass {
width: 720
height: 540
}
instead of using a VideoPreset().resolution

**Comment by davidliu** [comment]
Yeah, the camera only supports certain resolutions, so the webrtc library finds the closest resolution possible to the requested resolution.

https://github.com/react-native-webrtc/react-native-webrtc/blob/42560e978c77f93802461d32cac19cce1e76e2db/ios/RCTWebRTC/VideoCaptureController.m#L210C2-L210C2
